name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # フル履歴をフェッチ

      # 必要なツールをインストール
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make

      # 変更されたファイルを取得
      - name: Get changed test files
        id: changed_tests
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt || true
          grep "tests/.*\.cpp" changed_files.txt | xargs -I{} basename {} > changed_tests.txt || true
        shell: bash

      # プロジェクトのビルド
      - name: Build project
        run: |
          mkdir -p build
          cd build
          cmake ..
          cmake --build .

      # テストの実行
      - name: Run tests
        run: |
          cd build
          if [ -s ../changed_tests.txt ]; then
            while read TEST; do
              echo "Running $TEST"
              ./$TEST
            done < ../changed_tests.txt
          else
            echo "No relevant test cases to run."
          fi
